연산자, 반복문 추가
howCanWeDoVeryWell/CodeReview pull request #7
Opened 2018-08-21 13:10 UTC by shinyeonjong

확인 부탁드립니다.

2018-08-21 16:08 UTC, imcts requested changes
전반적으로 컨벤션이 안맞추어져있고 

사용자의 입력과 

메소드의 수행결과와 

출력이 구분되어 있지 않음. 


상수를 제대로 정의하고 컨벤션에 맞춰 사용하지 않았음. 그 부분 고민해보면 좋을듯.

2018-08-21 16:08 UTC, imcts commented on sujin/src/homework/operator/Ch02_Variable2_3.java
> + * 4. ?��?��받�? ?��?�� ?��?��?��리�?? 1�? 바꾸?�� 코드�? ?��?��?��?��?��
남의 코드는 건드리지말자.

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter01/IdentifyNumber.java
> +        long indentityNumber = 94122200000000L;
주민등록 번호는 문자열아니었어?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public static void tryTernaryOperation () {
try는 무언가를 시도하다니까 이것보다는 do가 나음. 하지만 이 메소드는 사실상 int 정수를 입력받아서 그 값을 가지고 양수와 음수 0을 반환받아야 하는거 아님 ? 왜 여기에서 출력까지 하지?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +        int userAnswer = scanUserAnswer();
1. 0 입력 하면 어떻게돼
2. 왜 여기에서 입력을 받아.
3. 왜 여기에서 출력하지.

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +        int userAnswer = scanUserAnswer();
1. 0 입력 하면 어떻게돼
2. 왜 여기에서 입력을 받아.
3. 왜 여기에서 출력하지.

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public static void multiple() {
메소드명은 동사 + 명사
메소드명 뒤에 공백.

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public static void multiple() {
1. 0 입력 하면 어떻게돼
2. 왜 여기에서 입력을 받아.
3. 왜 여기에서 출력하지.

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            return userAnswer = answerScanner.nextInt();
왜 대입하자마자 반환할건데 대입을 하지?

```java
return answerScanner.nextInt();
``` 
하면 안되나?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            scanUserAnswer();
만약 에러가 나서 여기에 진입해서 scanUserAnsewr를 재귀로 호출 했는데 그다음에 호출한다음에 userAnswer를 반환하면 그냥 0만 반환되나 ? 그러면 니 로직에서는 0받으면 다 작살나는거 같던데 그게 원하는 결과인가?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            scanUserAnswer();
테스트는 해봤나?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public static void selectedQuestion() {
뭔지 모르겠지만 메소드명이 selectedQuestion이 아니라 selectQuestion이어야 할듯. 
selected는 선택된 이라는 뜻임. 선택하라고 하고 싶은거면 select

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +                case 1 :
1은 뭐야.

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +                case 2 :
2는 뭐야

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +                case 3 :
3은 뭐야

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +                case 4 :
4는 뭐야

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +                case 5 :
5는 뭐야

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            selectedQuestion = questionScanner.nextInt();
어차피 숫자 받을거면 scanUserAnswer 이거면 되는거 아님 ?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public static int scanUserAnswer() {
scan은 살펴보다 훑어보다는건데 유저의 답변을 살펴보는게 목적임 ?

getUserInput 정도가 맞을듯.

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public static int scanUserAnswer() {
만약 숫자만 받을거라면 getUserInputNumber

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            selectedQuestion();
에러나면 또 재귀로 불러 ? 이게 맞어 ?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            selectedQuestion();
대체 이 반복문은 그럼 몇번 호출돼 ?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public static void showQuestions() {
이건 showQuestions()가 아니라 showMenu()일거 같고 굳이 이렇게 한다음에 입력 받으러 감 ?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +    public static void convertFahrenheitToCelsius() {
👍

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +            System.out.println("섭씨를 입력하세요.");
메소드명이랑 하는일은 완전 다른데 

1. 입력을 받고

2. 계산을 한다음에 

3. 출력까지 하시겠다?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +            int result = celsius = 5 / 9 * (fahrenheit - 32);
5는 뭐야 

9는 뭐야

32는 뭐야

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +            convertFahrenheitToCelsius();
재귀를 알고 쓰는게 아닌거 같은데 다시 한번 생각해봐 이게 맞어 ?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +    public static void checkNumber() {
숫자일때만 true반환하기인데 반환자료형이 void.

1. 입력을 받고

2. 계산을 하고 

3. 출력까지 하시겠다.?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +            if (ascii >= 48 && ascii <= 57) {
48은 뭐야

57은 뭐야

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +                //System.out.println("convert toLower" + userAnswer[i]);
주석 제거

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +                continue;
컨티뉴가 있어야 하는 이유.

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +                continue;
컨티뉴는 왜

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +                userAnswer[i] = (char) Character.toString(userAnswer[i]).toUpperCase().charAt(0);
이럴거면 그냥 대놓고 toUpperCase() toLowerCase()쓰면 될일 아닌가? 이건 원하는 방식이 아닌듯. 
아스키 코드를 가지고 놀거면 아스키 코드로 확실히 놀아야지. 대문자와 소문자의 차이는 몇일까.

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +    public static void selectedQuestion() {
마찬가지. selected 아니고 select.

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +                case 1 :
케이스 상수로 분리.

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +            if(!(i % exceptionNumber1 == 0 || i % exceptionNumber2 == 0)) {
```java
 if(!(i % exceptionNumber1 == 0 || i % exceptionNumber2 == 0))
```

```java
 if (i % exceptionNumber1 != 0 && i % exceptionNumber2 != 0)
```

???

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        int exceptionNumber1 = 2;
exception말고 disabledNumber 정도가 나을듯. 
그리고 이 값은 여기가 아니라 저 위에 전역으로 빠져야되는거 아니냐.

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        for (int i = 0; i < blackDice.length; i++) {
매번 length에 접근하는건 안 좋음.

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        int MaxNumber = 100;
대문자로 시작한다고?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +            shift *= -1;
쉬프트는 계속 -1을 곱하기만 하는데 이게 된다고 ? 이게 지금 동작한다구 ?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +            sumEach();
try catch 를 제대로 이해 못하고 재귀를 때리고 있음. 
왜 여기에서 재귀를 하는거지?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +    public static void fibonacci() {
미사용 메소드?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +    public static void discrimination() {
미사용 메소드?

2018-08-21 16:08 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +        //fibonacci();
주석 제거

2018-08-21 16:13 UTC, sirupe requested changes
전반적으로 매직넘버가 많아 따로 기재하지 않았습니다. 매직넘버나 공식은 추출해주셨음 좋겠습니다.

2018-08-21 16:13 UTC, sirupe commented on sujin/src/homework/operator/Ch02_Variable2_3.java
> +		System.out.print("?��?��?��?��?�� : ");
이렇게 필요없이 push 된 코드는 이력에서 삭제해주셨으면 좋겠습니다.

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter01/IdentifyNumber.java
> +        long indentityNumber = 94122200000000L;
주민등록번호를 초기화하는데 long 자료형을 사용한 이유는 무엇인가요? 이미 long 임을 알리는 L 이 맨 뒤에 붙음으로써 주민등록번호의 기능을 상실한 것이 아닌가요?

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +        int userAnswer = scanUserAnswer();
scanUserAnswer() 메소드의 위치가 tryTernaryOperation() 메소드 바로 아래이면 좋겠군요.

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +        String result = userAnswer > 0 ? "양수" : userAnswer < 0 ? "음수" : "0";
구글링으로 찾아낸 3항식에서 사용 가능한 세가지 방법입니다.
보기 좋은 방식을 채택하는 것이 좋을 것 같습니다.
```java
// 1.
String result = userAnswer > 0 ? "양수" : userAnswer < 0 ? "음수" : "0";
```
```java
// 2.
String result = userAnswer > 0 ? "양수"
                               : userAnswer < 0 ? "음수" 
                                                : "0";
```
```java
// 2.
String result = userAnswer > 0 
                ? "양수" 
                : userAnswer < 0 
                   ? "음수" 
                   : "0";
```

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +            selectedQuestion();
exception 이 발생했는데 왜 재귀를 돌리나요? exception 을 처리하지는 않나요 ?

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter02/Operator2.java
> +            convertFahrenheitToCelsius();
이렇게 재귀로 호출하면 사용자가 숫자를 잘못 입력할때마다 호출스택에 convertFahrenheitToCelsius() 메소드가 엄청나게 쌓이겠네요.

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter02/Operator2.java
> +                //System.out.println("convert toLower" + userAnswer[i]);
이런 주석은 지우는 것이 좋겠습니다.

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter02/Operator2.java
> +                continue;
이 시점에서 continue 를 쓴 이유가 있나요? 어차피 건너뛰고 싶은 코드가 없지 않습니까?

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter02/Operator2.java
> +                userAnswer[i] = (char) Character.toString(userAnswer[i]).toUpperCase().charAt(0);
문자열을 char 자료형으로 받았다면 구지 힘들게 toLowerCase(), toUpperCase() 쓰지 않고 수 연산으로 대소문자를 변경해도 될 것 같습니다.

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter02/Operator2.java
> +            selectedQuestion();
이렇게 한도끝도없이 재귀를 쌓다간 프로그램이 폭..파..되지 않을까요

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter03/Loop.java
> +    public static void sum1to10() {
차라리 sumOneToTen 이 더 낫지 않을까요

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter03/Loop.java
> +            if(!(i % exceptionNumber1 == 0 || i % exceptionNumber2 == 0)) {
만약 exceptionNumber 가 2와 3뿐만이 아니라 10개도 넘는다면? 이렇게 if 문 조건에 전부 집어넣으실 생각이신가요?

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter03/Loop.java
> +            sum = sum + i;
우리에게는 += 연산자가 있습니다.

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter03/Loop.java
> +            for (int j = 0; j < whiteDice.length; j++) {
blackDice = 2, whiteDice = 4 인 경우와 blackDice = 4, whiteDice = 2 인 경우는 같은 경우 아닌가요?

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter03/Loop.java
> +        int MaxNumber = 100;
지역변수는 대문자로 시작하지 않습니다.

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter03/Loop.java
> +            loopCount++;
loopCount 를 초기화도 할거고 ++ 연산도 할 거였으면 for문을 사용하는 것도 가능할 것 같은데 while 문으로 작성해야만 하는 이유가 있었나요?

2018-08-21 16:13 UTC, sirupe commented on yeonjong/src/chapter03/Loop2.java
> +    public static void fibonacci() {
아무것도 아닌 코드는 제외하고 올리는 걸로

2018-08-21 16:14 UTC, shinyeonjong commented on yeonjong/src/chapter01/IdentifyNumber.java
> +        long indentityNumber = 94122200000000L;
음 문제에 그런 조건은 없어서 long으로 했습니다.

2018-08-21 16:18 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +            shift *= -1;
네.

2018-08-21 16:20 UTC, shinyeonjong commented on sujin/src/homework/operator/Ch02_Variable2_3.java
> + * 4. ?��?��받�? ?��?�� ?��?��?��리�?? 1�? 바꾸?�� 코드�? ?��?��?��?��?��
x(

2018-08-21 16:27 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +    public static void fibonacci() {
수정

2018-08-21 16:28 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +            for (int j = 0; j < whiteDice.length; j++) {
경우의 수라면 중복이 아니라고 생각합니다.
(1, 5) / (2, 4) / (3, 3) / (4, 2) / (5, 1)

2018-08-21 16:28 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +            sum = sum + i;
히히

2018-08-21 16:31 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +            selectedQuestion();
InputMismatch 일 경우 함수를 다시 하게 끔 처리하고 싶어 재귀를 사용했으나
다른 방법을 사용하여 수정할 계획입니다.

2018-08-21 16:31 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +        String result = userAnswer > 0 ? "양수" : userAnswer < 0 ? "음수" : "0";
히히

2018-08-21 16:34 UTC, shinyeonjong commented on yeonjong/src/chapter01/IdentifyNumber.java
> +        long indentityNumber = 94122200000000L;
Integer number too long 에러가 났습니다.
다시 한번 확인해보겠습니다.

2018-08-21 16:36 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +        int MaxNumber = 100;
수정

2018-08-21 16:36 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +    public static void fibonacci() {
수정

2018-08-21 16:37 UTC, imcts commented on yeonjong/src/chapter01/IdentifyNumber.java
> +        long indentityNumber = 94122200000000L;
String으로 변경. 주민번호 포맷 맞추길 권함.

2018-08-21 16:42 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +            sumEach();
사용자가 입력받은값이 숫자가 아니면 다시 입력받게 하려고 했습니다

2018-08-21 16:45 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +        int userAnswer = scanUserAnswer();
tryTernaryOperation(), dumpHundreds(),  changeUnits(), multiple(), 에서 공통으로 스는 메소드 입니다. 왜 tryTernaryOperation() 아래면 좋은지 궁금해용

2018-08-21 16:48 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +            sumEach();
그럼 사용자가 메모리 영역만큼 잘못 입력하면 컴퓨터에는 블루 스크린이 발생하겠네.

2018-08-23 05:37 UTC, imcts reviewed
확인 부탁드립니다.

2018-08-23 05:37 UTC, imcts commented on yeonjong/src/chapter01/IdentifyNumber.java
> +
클래스와 메인메소드 사이의 불필요 공백 및 메인메소드 안에서의 불필요 공백, 메인메소드 아래부분의 공백 제거가 필요함.

2018-08-23 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public String doTernaryOperation(int userInputNumber) {
유저의 값을 전달받아서 매칭되는 문자열을 얻는게 이 메소드의 역할이므로 `getMatchedString`정도가 맞을듯 싶음.

2018-08-23 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +
공백제거.

2018-08-23 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public static final String QUESTION_FIVE = "5";
더 좋은 방법을 배우고 싶으면, 오빠를 만나는날 더 좋은 방법에 대해서 설명해 달라고 요청해볼것. 지금도 나쁘지 않음.

2018-08-23 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +        if (userInputNumber < 100) {
100의 자리 이하의 값을 전달 받으면 100이하를 버리면 되므로 
```java
  return userInputNumber; 
```
를 하면 되는거 아닌가?

2018-08-23 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public int changeUnits(int userInputNumber) {
Units는 의미가 너무 광범위하고 모호하므로 changeLastNumberToOne 정도면 더 좋을듯. 
사실상 유닛들을 바꾼다는건데 무슨 유닛들을 바꾼다는 것인지 알 수 없음.

2018-08-23 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            throw new InputMismatchException();
이건 기능이 이상한데? 10보다 작으면 10에서 입력받은 수를 빼야 하는거 아닌가? 왜 에러를 발생시키지.

2018-08-23 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +
공백제거

2018-08-23 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +                System.out.println(doTernaryOperation(getUserInputNumber()));
이 부분은 여기서 문제 삼지는 않겠으나, 만나면 물어볼 것 무엇이 문제인지.
working하는 코드이므로 패스함.

2018-08-23 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            operator.showMenu();
여기에서 다시 에러가 발생하면 어떻게돼 ?

2018-08-23 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        return celsius = 5 / 9 * (fahrenheit - 32);
이거 원래 공식이 뭐야? `celsius `를 인자로 받아놓고 celsius에 대입한다음에 그냥 반환한다구;??

2018-08-23 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        if (userInput >= ASCII_ONE && userInput <= ASCII_NINE) {
[질문] 0은 어떻게 돼.

2018-08-23 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        return isNumber;
```java
public boolean checkNumberType (int userInput) {
    return userInput >= ASCII_ONE && userInput <= ASCII_NINE;
}
```

2018-08-23 05:42 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +            operator.showMenu();
오늘 질문하려고 한 부분입니다...

2018-08-26 12:30 UTC, shinyeonjong reviewed
수정 사항 반영

2018-08-26 12:30 UTC, shinyeonjong commented on yeonjong/src/chapter01/IdentifyNumber.java
> +
수정

2018-08-26 12:30 UTC, shinyeonjong commented on yeonjong/src/chapter01/IdentifyNumber.java
> +        long indentityNumber = 94122200000000L;
수정

2018-08-26 12:30 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +    public static void tryTernaryOperation () {
수정

2018-08-26 12:30 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +            return userAnswer = answerScanner.nextInt();
수정

2018-08-26 12:30 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +                case 1 :
수정

2018-08-26 12:30 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +                continue;
첫번째 if문에 대문자 조건에 일치하여 소문자로 변경 후 if문을 나가게 되면
두번째 if문의 소문자 조건에 일치하게 되어다시 소문자로 변경된 대문자를 다시 소문자로 변경하기 때문에 
continue  를 사용하여 조건에 일치하면 for 문의 끝으로 이동하도록 하기위해 사용했습니다.

2018-08-26 12:30 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +                continue;
첫번째 if문에 대문자 조건에 일치하여 소문자로 변경 후 if문을 나가게 되면
두번째 if문의 소문자 조건에 일치하게 되어다시 소문자로 변경된 대문자를 다시 소문자로 변경하기 때문에
continue 를 사용하여 조건에 일치하면 for 문의 끝으로 이동하도록 하기위해 사용했습니다.

2018-08-26 12:30 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +                continue;
첫번째 if문에 대문자 조건에 일치하여 소문자로 변경 후 if문을 나가게 되면
두번째 if문의 소문자 조건에 일치하게 되어다시 소문자로 변경된 대문자를 다시 소문자로 변경하기 때문에
continue 를 사용하여 조건에 일치하면 for 문의 끝으로 이동하도록 하기위해 사용했습니다.

2018-08-26 12:37 UTC, shinyeonjong reviewed
수정사항 코멘트

2018-08-26 12:37 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +            sumEach();
수정

2018-08-26 12:37 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +        for (int i = 0; i < blackDice.length; i++) {
수정

2018-08-26 12:37 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +    public static void sum1to10() {
수정

2018-08-26 12:37 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +            if(!(i % exceptionNumber1 == 0 || i % exceptionNumber2 == 0)) {
수정

2018-08-26 12:37 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +            if(!(i % exceptionNumber1 == 0 || i % exceptionNumber2 == 0)) {
수정

2018-08-26 12:37 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +        int exceptionNumber1 = 2;
수정

2018-08-26 12:37 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +                userAnswer[i] = (char) Character.toString(userAnswer[i]).toUpperCase().charAt(0);
수정

2018-08-26 12:37 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +                userAnswer[i] = (char) Character.toString(userAnswer[i]).toUpperCase().charAt(0);
수정

2018-08-26 12:37 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +        if (userInput >= ASCII_ONE && userInput <= ASCII_NINE) {
수정

2018-08-26 12:37 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +        return celsius = 5 / 9 * (fahrenheit - 32);
수정

2018-08-26 12:37 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +
수정

2018-08-26 12:57 UTC, imcts commented on yeonjong/src/chapter01/IdentifyNumber.java
> +        long indentityNumber = 94122200000000L;
ok

2018-08-26 12:58 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public static void tryTernaryOperation () {
ok

2018-08-26 12:59 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +                continue;
그럼 if 이후에 if else문을 사용하는게 더 읽기 좋지 않을까?

2018-08-26 13:00 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +                continue;
그럼 if 이후에 if else문을 사용하는게 더 읽기 좋지 않을까?

2018-08-26 13:23 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +        int userAnswer = scanUserAnswer();
1. getUserInput 메소드에서 체크하도록 수정했습니다.
 > if (userInputValue <= MIN_NUMBER) 
2. 입력받는 scanUserInputValue 메소드 추가했습니다.
3. 출력하는 getAnswerToQuestion 메소드 추가했습니다.

2018-08-26 13:23 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +        int userAnswer = scanUserAnswer();
1. getUserInput 메소드에서 체크하도록 수정했습니다.
 > if (userInputValue <= MIN_NUMBER) 
2. 입력받는 scanUserInputValue 메소드 추가했습니다.
3. 출력하는 getAnswerToQuestion 메소드 추가했습니다.

2018-08-26 13:23 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +    public static void fibonacci() {
삭제했습니다.

2018-08-26 13:23 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +    public static void discrimination() {
삭제했습니다.

2018-08-26 13:23 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +        //fibonacci();
삭제했습니다.

2018-08-26 13:24 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +            selectedQuestion();
수정했습니다.

2018-08-26 13:26 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +        if (userInputNumber < 100) {
수정

2018-08-26 13:26 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +                System.out.println(doTernaryOperation(getUserInputNumber()));
1. 입력받는 scanUserInputValue 메소드 추가했습니다.
2. 출력하는 getAnswerToQuestion 메소드 추가했습니다.

2018-08-26 13:27 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +        return isNumber;
checkNumber 메소드로 수정했습니다.

2018-08-26 13:31 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +        if (userInput >= ASCII_ONE && userInput <= ASCII_NINE) {
checkNumber 메소드로 수정했습니다.

2018-08-26 13:31 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +        return celsius = 5 / 9 * (fahrenheit - 32);
수정했습니다

2018-08-26 13:31 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +            throw new InputMismatchException();
수정했습니다.

2018-08-26 13:31 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +
수정했습니다.

2018-08-26 13:32 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +    public int changeUnits(int userInputNumber) {
changeLastUnits 으로 수정했습니다.

2018-08-26 13:32 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +        if (userInputNumber < 100) {
수정했습니다.

2018-08-26 13:32 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +
수정했습니다.

2018-08-26 13:32 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +    public static void fibonacci() {
수정했습니다.

2018-08-26 13:32 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +        int MaxNumber = 100;
수정했습니다.

2018-08-26 13:32 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +            if(!(i % exceptionNumber1 == 0 || i % exceptionNumber2 == 0)) {
수정했습니다.

2018-08-26 13:33 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +            if(!(i % exceptionNumber1 == 0 || i % exceptionNumber2 == 0)) {
> int[] disabledNumber = {DISABLED_NUMBER_TWO, DISABLED_NUMBER_THREE};
배열로 받아 처리하는 방식으로 수정했습니다.

2018-08-26 13:34 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +    public static void sum1to10() {
수정했습니다.

2018-08-26 13:34 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +            selectedQuestion();
수정했습니다

2018-08-26 13:35 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +                userAnswer[i] = (char) Character.toString(userAnswer[i]).toUpperCase().charAt(0);
convertAlphabetic() 메소드를
대문자와 소문자의 ASCII code 가 32씩 차이난다는 점을 반영하여 수정했습니다.

2018-08-26 13:45 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +                continue;
if else 를 사용해 다시 수정했습니다.

2018-08-26 13:45 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +                //System.out.println("convert toLower" + userAnswer[i]);
수정했습니다.

2018-08-26 13:46 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +            convertFahrenheitToCelsius();
수정했습니다.

2018-08-26 13:46 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +            shift *= -1;
수정했습니다.

2018-08-26 13:46 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +            sumEach();
수정했습니다.

2018-08-26 13:46 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +        int MaxNumber = 100;
수정했습니다.

2018-08-26 13:46 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +        for (int i = 0; i < blackDice.length; i++) {
수정했습니다.

2018-08-26 13:48 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +        int exceptionNumber1 = 2;
수정했습니다.

2018-08-26 13:48 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +            if(!(i % exceptionNumber1 == 0 || i % exceptionNumber2 == 0)) {
수정했습니다.

2018-08-26 13:49 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +                userAnswer[i] = (char) Character.toString(userAnswer[i]).toUpperCase().charAt(0);
32씩 차이난다는 점을 적용하여 수정했습니다.

2018-08-26 13:49 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +                continue;
수정했습니다.

2018-08-26 13:49 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +                continue;
수정했습니다.

2018-08-26 13:49 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +                //System.out.println("convert toLower" + userAnswer[i]);
수정했습니다.

2018-08-26 13:49 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +            if (ascii >= 48 && ascii <= 57) {
수정했습니다.

2018-08-26 13:49 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +    public static void checkNumber() {
수정했습니다.

2018-08-26 13:50 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +            int result = celsius = 5 / 9 * (fahrenheit - 32);
전역으로 수정했습니다.

2018-08-26 13:50 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +            System.out.println("섭씨를 입력하세요.");
수정했습니다

2018-08-26 13:51 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +                case 1 :
상수로 분리했습니다.

2018-08-26 13:51 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +                case 2 :
상수로 분리했습니다.

2018-08-26 13:51 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +                case 3 :
상수로 분리했습니다.

2018-08-26 13:52 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +                case 4 :
상수로 분리했습니다.

2018-08-26 13:52 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +                case 5 :
상수로 분리했습니다.

2018-08-27 02:55 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +        int userAnswer = scanUserAnswer();
ok

2018-08-27 02:55 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +        int userAnswer = scanUserAnswer();
ok

2018-08-27 02:55 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public static void multiple() {
ok

2018-08-27 02:55 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            return userAnswer = answerScanner.nextInt();
ok

2018-08-27 02:56 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public static void selectedQuestion() {
ok

2018-08-27 02:56 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            scanUserAnswer();
selectedQuestion

2018-08-27 02:56 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +                case 1 :
ok

2018-08-27 02:56 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +                case 2 :
ok

2018-08-27 02:56 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +                case 3 :
ok

2018-08-27 02:56 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +                case 4 :
ok

2018-08-27 02:56 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +                case 5 :
ok

2018-08-27 02:57 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            selectedQuestion = questionScanner.nextInt();
ok

2018-08-27 02:58 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public static void showQuestions() {
ok

2018-08-27 02:58 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +    public static void convertFahrenheitToCelsius() {
ok

2018-08-27 02:58 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +            System.out.println("섭씨를 입력하세요.");
ok

2018-08-27 02:58 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +            int result = celsius = 5 / 9 * (fahrenheit - 32);
ok

2018-08-27 03:39 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +    public static void checkNumber() {
ok

2018-08-27 03:39 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +            if (ascii >= 48 && ascii <= 57) {
ok

2018-08-27 03:39 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +                //System.out.println("convert toLower" + userAnswer[i]);
ok

2018-08-27 03:39 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +                continue;
ok

2018-08-27 03:39 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +                continue;
ok

2018-08-27 03:39 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +                userAnswer[i] = (char) Character.toString(userAnswer[i]).toUpperCase().charAt(0);
ok

2018-08-27 03:39 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +                case 1 :
ok

2018-08-27 03:39 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +            if(!(i % exceptionNumber1 == 0 || i % exceptionNumber2 == 0)) {
ok

2018-08-27 03:39 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        int exceptionNumber1 = 2;
ok

2018-08-27 03:40 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        for (int i = 0; i < blackDice.length; i++) {
ok

2018-08-27 03:40 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        int MaxNumber = 100;
ok

2018-08-27 03:40 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +            shift *= -1;
ok

2018-08-27 03:40 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +            sumEach();
ok

2018-08-27 03:40 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +    public static void fibonacci() {
ok

2018-08-27 03:40 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +    public static void discrimination() {
ok

2018-08-27 03:40 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +        //fibonacci();
ok

2018-08-27 03:40 UTC, imcts commented on yeonjong/src/chapter01/IdentifyNumber.java
> +
ok

2018-08-27 03:40 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +
ok

2018-08-27 03:41 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +        if (userInputNumber < 100) {
ok

2018-08-27 03:41 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +    public int changeUnits(int userInputNumber) {
ok

2018-08-27 03:41 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            throw new InputMismatchException();
ok

2018-08-27 03:41 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +
ok

2018-08-27 03:41 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +                System.out.println(doTernaryOperation(getUserInputNumber()));
ok

2018-08-27 03:41 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            operator.showMenu();
ok

2018-08-27 03:41 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        return celsius = 5 / 9 * (fahrenheit - 32);
ok

2018-08-27 03:41 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        if (userInput >= ASCII_ONE && userInput <= ASCII_NINE) {
ok

2018-08-27 03:42 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        return isNumber;
ok

2018-08-27 05:37 UTC, imcts reviewed
1. 메소드 뒤에는 공백 추가.
2. 배열 선언 앞뒤로 공백 추가.

2018-08-27 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        showMenu();
`run`메소드는 메뉴를 보여주는 역할로 한정 지어지면 안될 것 같은데 ㅎㅎ
1. 메뉴를 보여준다.
2. 메뉴에서 선택된 값을 반환받는다.
3. 메뉴에 맞는 입력을 받는다. 
4. 문제를 실행시킨다.
5. 실행된 문제의 결과값을 출력한다.

2018-08-27 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        try {
1. 문제를 노출하기만 해야 하는데 문제를 선택도 하게 하고있어. 그러면 `showMenu`가 아닌것 같은데. 
2. catch 구문 안에서 show 메뉴를 다시 호출한다면 이건 `try, catch`를 잘못 이해하고 있는 것임. 만약에 catch 문에서 호출한 `showMenu`에서 또 에러가 발생한다면 그땐 어떻게 될까?

2018-08-27 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        checkQuestionNumber(questionNumber);
여기에서도 메뉴를 선택하고나서 선택 받은 결과값을 반환해야 하는데 문제 넘버까지 하려고 하니 문제가 생기는 것.

- 메뉴를 보여주는 메소드
- 사용자에게 숫자를 입력 받고 유효한지 검사하고, 유효한 값이라면 반환하는 메소드
- 사용자에게 입력 받은 값을 가지고 문제를 실행하는 메소드로 나뉘어져야 함.

2018-08-27 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        char[] compareChar = userInput.toCharArray();
1. `char[] compareChar` => `char [] chars` 공백 추가 및 chars 복수 선언.
2. userInput이 null이라면 이 코드는 어떻게 됨?

2018-08-27 05:37 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        }
```java
for (int i = 0, len = chars.length; i < len; i++) {
  char unit = chars[i];
  if (unit >= ASCII_UPPER_CASE_A && unit <= ASCII_UPPER_CASE_Z) {
    chars[i] += ALPHABET_RANGE;
  } else {
    if (unit >= ASCII_LOWER_CASE_A && unit <= ASCII_LOWER_CASE_Z) {
      chars[i] -= ALPHABET_RANGE;
    }
  }
}
```

1. 코드의 mandatory를 맞추면 더 읽기 쉬운 코드가 됨.
2. 배열의 특정방을 매번 접근하는 것 보다 변수를 하나 할당하는 편이 훨씬 효율적.

2018-08-27 05:37 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        int[] disabledNumber = {DISABLED_NUMBER_TWO, DISABLED_NUMBER_THREE};
`int [] number`, `int [] disabledNumber` 공백 추가.

2018-08-27 05:37 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        System.out.println("---- sumMultiple result ----");
1부터 20까지 순회하면서 2의 배수 또는 3의 배수가 아닌 경우에 합을 하면 되는게 문제라면
대체 왜 이렇게 for문을 미친듯이 돌아야 하는걸까? 1부터 20까지 한번만 돌면 될 일인데.

2018-08-27 05:37 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        for (int i = 0, blackDiceSize = blackDice.length; i < blackDiceSize; i++) {
`blackDiceSize ` => `blackDiceLength` 배열이기 때문에 length로 표현해주어야 맞을듯.

2018-08-27 05:37 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        while (currentNumber <= maxNumber) {
수정하라는건 아니지만 이건 for문을 사용하는게 더 좋았을듯.

2018-08-27 05:37 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +    public static void main(String[] args) {
`String [] args` 공백 추가.
메소드명 뒤에 공백 추가.

2018-08-27 05:37 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +    // 입력 받은 수 각각 더하기
입력 받은 수 각각 더하기라는 문제인데, 내용은 전혀 이해가 안감; 
왜 계속 나누는건지 설명을 추가해야 할 듯.

2018-08-27 05:37 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +        try {
이 아래부분은 왜 필요한 코드인지 모르겠음. 안 쓰이는데 전혀;

2018-08-27 11:22 UTC, sirupe reviewed
리뷰확인요청

2018-08-27 11:22 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +            throw new InputMismatchException();
Exception 발생시키는 것은 없어도 될 것 같음. 그리고 10보다 작은 수도 계산이 되어야 할 것 같음.

2018-08-27 11:22 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +            showMenu();
문제가 여전히 재귀로 호출되고 있네~ ( line 45, 51, 60, 66 동일)

2018-08-27 11:22 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +        }
이 메소드 자체가 잘 이해가 안가. 없는 문제입니다 라는 멘트가 굉장히 여러번 등장하네 ? showMenu 에서도 본 것 같은데. 그리고 selectMenu 에서 이미 메뉴넘버를 입력받아서 넘어온 것 같은데 getUserInput 메소드가 왜 호출되는지 잘 모르겠어. 그리고 getUserInput 인데 반환자료형이 void 라서 어떤 작업을 하려고 저 메소드를 호출했는지 이해가 잘 안돼.

2018-08-27 11:22 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +    public int scanUserInputValue() throws InputMismatchException {
return 만 다를 뿐이지 selectMenu 와 같은 기능을 하는 메소드처럼 보이네.

2018-08-27 11:22 UTC, sirupe commented on yeonjong/src/chapter02/Operator2.java
> +    public String scanUserInputValue() throws InputMismatchException {
chapter01 이랑도 많이 중복되는데 아예 common 클래스로 분리했어도 괜찮았겠다.

2018-08-27 11:23 UTC, sirupe commented on yeonjong/src/chapter01/IdentifyNumber.java
> +        long indentityNumber = 94122200000000L;
ok

2018-08-27 11:26 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +        int userAnswer = scanUserAnswer();
코드를 읽어내려갈 때 해당 메소드가 처음 사용된 곳 바로 아래에 등장하는 것이 읽기가 편할 것이라 생각해. (참조 : 클린코드) 그 아래에서 해당 메소드를 또 사용한다면 이미 있다는 것을 아니 코드 내용을 확인할 것이 아니라면 다시 올라가지 않아도 괜찮겠지만 그 메소드를 사용한 모든 메소드 아래에 해당 메소드가 있다면 처음 등장하는 코드에서는 그 메소드를 찾기 위해 스크롤을 한참 내려야겠지 ?

2018-09-02 05:01 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +    public String scanUserInputValue() throws InputMismatchException {
chapter02.common.UserInput 에   입력받는 함수들을 따로 분리했습니다.

2018-09-02 05:01 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +    public int scanUserInputValue() throws InputMismatchException {
chapter02.common.UserInput 에 입력받는 함수들을 따로 분리했습니다.

2018-09-02 05:04 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +        }
execute 메소드에서 
int selectedMenu = UserInput.getUserInteger(); 로 사용자의 메뉴 입력을 받고
int userInputValue = UserInput.getUserInteger(); 로 사용자의 입력 값을 받고
String result = executeQuestionBy(selectedMenu, userInputValue); 문제를 풀어 결과값을 받는 로직으로 수정했습니다.

2018-09-02 05:05 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +            showMenu();
execute 메소드에서 while문을 사용하는 방식으로 수정했습니다.

2018-09-02 05:05 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +            throw new InputMismatchException();
수정했습니다.

2018-09-02 05:37 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +        try {
main() 함수 실행 부분을 수정했습니다.

2018-09-02 06:06 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +    // 입력 받은 수 각각 더하기
123 을 입력 받았을때

sum => 123 % 10 = 3
userInputNumber => 123 / 10 = 12

sum => 12 % 10 = 2
userInputNumber => 12 / 10 = 1

sum => 1 % 10 = 1
userInputNumber => 1 / 10 = 0

userInputNumber == 0 으로 종료

사용자의 입력 받은 값을 뒤에서부터 한자리씩 더하려고 했습니다.

2018-09-02 06:07 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +        for (int i = 0, blackDiceSize = blackDice.length; i < blackDiceSize; i++) {
수정완료

2018-09-02 06:07 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +        System.out.println("---- sumMultiple result ----");
sumMultiple () 함수 수정했습니다.

2018-09-02 06:07 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +        System.out.println("---- sumMultiple result ----");
sumMultiple () 함수 수정했습니다.

2018-09-02 06:08 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +        int[] disabledNumber = {DISABLED_NUMBER_TWO, DISABLED_NUMBER_THREE};
수정했습니다.

2018-09-02 06:09 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +        }
convertAlphabetic() 수정했습니더.

2018-09-02 06:13 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +        char[] compareChar = userInput.toCharArray();
2. 아무키나 입력하세요.
    please Input 
[결과]    PLEASE iNPUT 

공백은 공백입니다..

2018-09-02 06:19 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +        checkQuestionNumber(questionNumber);
execute 메소드에서
showMenu 로 메뉴를 보여주고
UserInput.getUserInteger(); 로 사용자의 숫자를 입력받고 유효 검사를 하고
executeQuestionBy(userSelectMenu, userInputValue); 로 문제를 실행하는 메소드로 구분지었습니다.

2018-09-02 06:19 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +        try {
execute 메소드에서
showMenu 로 메뉴를 보여주고
UserInput.getUserInteger(); 로 사용자의 숫자를 입력받고 유효 검사를 하고
executeQuestionBy(userSelectMenu, userInputValue); 로 문제를 실행하는 메소드로 구분지었습니다.

2018-09-02 06:19 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +        showMenu();
execute 메소드에서
showMenu 로 메뉴를 보여주고
UserInput.getUserInteger(); 로 사용자의 숫자를 입력받고 유효 검사를 하고
executeQuestionBy(userSelectMenu, userInputValue); 로 문제를 실행하는 메소드로 구분지었습니다.

2018-09-02 06:20 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +    // 입력 받은 수 각각 더하기
123 을 입력 받았을때

sum => 123 % 10 = 3
userInputNumber => 123 / 10 = 12

sum => 12 % 10 = 2
userInputNumber => 12 / 10 = 1

sum => 1 % 10 = 1
userInputNumber => 1 / 10 = 0

userInputNumber == 0 으로 종료

사용자의 입력 받은 값을 뒤에서부터 한자리씩 더하려고 했습니다.

2018-09-02 06:51 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +        execute();
`execute`와 `run`의 차이가 뭐길래 run과 execute를 분리한건지에 대한 설명이 필요함. 
왜 run메소드와 execute메소드를 분리한거야?

2018-09-02 06:51 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        showMenu();
ok

2018-09-02 06:51 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        try {
ok

2018-09-02 06:51 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        checkQuestionNumber(questionNumber);
ok

2018-09-02 06:53 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        char[] compareChar = userInput.toCharArray();
```java
public String convertAlphabetic(String userInput) {
    // userInput == null 인 상황이면 어떻게 돼 ?
}
```

2018-09-02 06:53 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +        }
ok

2018-09-02 06:53 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        int[] disabledNumber = {DISABLED_NUMBER_TWO, DISABLED_NUMBER_THREE};
ok

2018-09-02 06:54 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        System.out.println("---- sumMultiple result ----");
이것도 문제를 잘 이해를 못한듯.

2018-09-02 06:54 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        for (int i = 0, blackDiceSize = blackDice.length; i < blackDiceSize; i++) {
ok

2018-09-02 06:55 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +    public static void main(String[] args) {
ok

2018-09-02 08:20 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +        execute();
execute와 run의 차이가 뭐길래 run과 execute를 분리한건지에 대한 설명이 필요함.
왜 run메소드와 execute메소드를 분리한거야?

2018-09-02 08:20 UTC, imcts commented on yeonjong/src/chapter02/Operator.java
> +            if (selectedMenu == Loop.FINISH) {
얘도 private 메소드로 분리하면 어때.

2018-09-02 08:20 UTC, imcts commented on yeonjong/src/chapter02/Operator2.java
> +            if (unit >= ASCIICode.UPPER_CASE_A && unit <= ASCIICode.UPPER_CASE_Z) {
```java
if (unit >= ASCIICode.UPPER_CASE_A && unit <= ASCIICode.UPPER_CASE_Z) {
   unit += ALPHABET_RANGE;
} else {
    if (unit >= ASCIICode.LOWER_CASE_A && unit <= ASCIICode.LOWER_CASE_Z) {
       unit -= ALPHABET_RANGE;
    }
}
```

```java
boolean isUpperCase = unit >= ASCIICode.UPPER_CASE_A && unit <= ASCIICode.UPPER_CASE_Z;
boolean isLowerCase = unit >= ASCIICode.LOWER_CASE_A && unit <= ASCIICode.LOWER_CASE_Z;
if (isUpperCase) {
   unit += ALPHABET_RANGE;
} else {
    if (isLowerCase) {
       unit -= ALPHABET_RANGE;
    }
}
```


```java
if (isUpperCase()) {
   unit += ALPHABET_RANGE;
} else {
    if (isLowerCase()) {
       unit -= ALPHABET_RANGE;
    }
}
```

2018-09-02 08:20 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +        int startNumber = 1;
```java
int STATRT_NUMBER = 1;
int END_NUMBER = 20;
int [] DISABLED_NUMBERS = {};
```

```java
int STATRT_NUMBER = 1;
int END_NUMBER = 20;
int List<Integer> DISABLED_LIST = Array.asArray({DISABLED_NUMBER_TWO, DISABLED_NUMBER_THREE});
```

2018-09-02 08:20 UTC, imcts commented on yeonjong/src/chapter03/Loop.java
> +            int sumValue = i;
```java
if (!DISABLED_LIST.contains(i)) {
   sum += i;
}
```

2018-09-02 08:20 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +            userInputNumber = userInputNumber / DIVISION_NUMBER;
```java
sum += userInputNumber % DIVISION_NUMBER;
userInputNumber /= DIVISION_NUMBER;
```

2018-09-02 08:20 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +    // 입력 받은 수 각각 더하기
ok.

2018-09-02 08:21 UTC, imcts approved these changes
유선상으로 말한내용 수정 되면 한번 알려만 주세요.

2018-09-02 08:21 UTC, imcts commented on yeonjong/src/chapter03/Loop2.java
> +    public void sumEach(int userInputNumber) {
주석을 알기 쉽게 재작성 하세요

2018-09-02 08:26 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +            throw new InputMismatchException();
`ok`

2018-09-02 08:27 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +            showMenu();
ok

2018-09-02 08:27 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +        }
ok

2018-09-02 08:31 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +    public int scanUserInputValue() throws InputMismatchException {
ok

2018-09-02 08:31 UTC, sirupe commented on yeonjong/src/chapter02/Operator2.java
> +    public String scanUserInputValue() throws InputMismatchException {
ok

2018-09-02 10:04 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +    public void sumEach(int userInputNumber) {
```java
// 입력 받은수의 자리수 각각 
```
주석 변경했습니다.

2018-09-02 10:06 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop2.java
> +            userInputNumber = userInputNumber / DIVISION_NUMBER;
```java
sum += userInputNumber % DIVISION_NUMBER;
userInputNumber /= DIVISION_NUMBER;
```
수정했습니다.

2018-09-02 10:07 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +            int sumValue = i;
₩₩₩java
// 1 ~ 20 중에 2배수 3배수 제외하고 합
    public static void sumMultiple() {
        int START_NUMBER = 1;
        int END_NUMBER = 20;
        int sum = 0;
        List<Integer> DISABLED_LIST = Arrays.asList(DISABLED_NUMBER_TWO, DISABLED_NUMBER_THREE);

        for (int i = START_NUMBER; i <= END_NUMBER; i++) {
            int sumValue = i;
            for (Integer disabledNumber : DISABLED_LIST) {
                if (i % disabledNumber != 0) {
                    sumValue = 0;
                }
            }
            sum += sumValue;
        }
        System.out.println("---- sumMultiple result ----");
        System.out.println("sum" + sum);
    }
₩₩₩

2018-09-02 10:48 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +        int startNumber = 1;
```java
List<Integer> DISABLED_LIST = Arrays.asList(DISABLED_NUMBER_TWO, DISABLED_NUMBER_THREE);
```
로 수정했습니다.

2018-09-02 10:50 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +            if (unit >= ASCIICode.UPPER_CASE_A && unit <= ASCIICode.UPPER_CASE_Z) {
```java
 private boolean isUpperCase(char unit) {
       return unit >= ASCIICode.UPPER_CASE_A && unit <= ASCIICode.UPPER_CASE_Z;
    }

    private boolean isLowerCase(char unit) {
        return unit >= ASCIICode.LOWER_CASE_A && unit <= ASCIICode.LOWER_CASE_Z;
    }
```

isUpperCase 대문자를 체크하는 함수와
isLowerCase 소문자를 체크하는 함수를 추가했고

```java
if (isUpperCase(unit)) {
  unit += ALPHABET_RANGE;
} else {
  if (isLowerCase(unit)) {
    unit -= ALPHABET_RANGE;
  }
}
```
위와같이 수정했습니다.

2018-09-02 10:52 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +            if (selectedMenu == Loop.FINISH) {
```java
private boolean isFinish(int selectedMenu) {
        if (selectedMenu == Loop.FINISH) {
            return true;
        } else {
            return false;
        }
    }
```

위와 같이 종료를 체크하는 함수를 추가했습니다.

2018-09-02 10:55 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +        execute();
```java
private void run() {
        int count = 0;
        while (count++ < Loop.MAX_COUNT) {
            if (execute()) {
                break;
            }
        }
        print("프로그램을 종료합니다.");
    }

    private boolean execute() {
        showMenu();
        int selectedMenu = UserInput.getUserInteger();
        if (!isFinish(selectedMenu)) {
            int userInputValue = UserInput.getUserInteger();
            String result = executeQuestionBy(selectedMenu, userInputValue);
            print(result);
            return false;
        }
        return true;
    }
```

프로그램을 실행하는 run() 메소드
문제를 선택하고, 문제에대한 입력값을 받고, 결과값을 출력하는 함수를 execute()메소드로 분리했습니다.

2018-09-02 10:56 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +        while (currentNumber <= maxNumber) {
ok

2018-09-02 10:57 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator2.java
> +        char[] compareChar = userInput.toCharArray();
```java
// 3. 대문자는 소문자로, 소문자는 대문자로 반환하기
    private String convertAlphabetic(String userInput) {
        if (userInput != null) {
            char [] chars = userInput.toCharArray();
            for (int i = 0, size = chars.length; i < size; i++) {
                char unit = chars[i];
                if (isUpperCase(unit)) {
                    unit += ALPHABET_RANGE;
                } else {
                    if (isLowerCase(unit)) {
                        unit -= ALPHABET_RANGE;
                    }
                }
                chars[i] = unit;
            }
            return String.valueOf(chars);
        } else {
            return null;
        }
    }
```

if (userInput != null)  을 추가했습니다.

2018-09-02 12:10 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +        execute();
```java
private boolean execute() {
        showMenu();
        int selectedMenu = UserInput.getUserInteger();
        if (isFinish(selectedMenu)) {
            return true;
        } else {
            int userInputValue = UserInput.getUserInteger();
            String result = executeQuestionBy(selectedMenu, userInputValue);
            print(result);
            return false;
        }
    }
```

if문에 들어가야하는 조건 중 특별한 경우가 아니라면 (if와 else가 다 존재한다면) 
if문에는 참 조건이 실행되는게 읽기에 좋아. 

그러므로 만약 종료라면 return true를 아니라면 false를 반환하게 해야 명시적인 코드가 될 거야. 
이 부분은 수정하면 좋을듯.

2018-09-02 12:12 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +            if (selectedMenu == Loop.FINISH) {
ㅋㅋ 의도는 좋았는데 불필요한게 들어있어. 

```java
    private boolean isFinish(int selectedMenu) {
        return selectedMenu == Loop.FINISH
    }
```
이거면 충분하지 않겠어 ?

2018-09-02 12:12 UTC, sirupe commented on yeonjong/src/chapter02/Operator2.java
> +            if (unit >= ASCIICode.UPPER_CASE_A && unit <= ASCIICode.UPPER_CASE_Z) {
ok

2018-09-02 12:18 UTC, sirupe commented on yeonjong/src/chapter03/Loop.java
> +        int startNumber = 1;
ok

2018-09-02 12:21 UTC, sirupe commented on yeonjong/src/chapter03/Loop.java
> +            int sumValue = i;
```java
            if (i % disabledNumber == 0) {
                sumValue = 0;
            }
```
이렇게 되어야 하지 않을까? 이거 실행 시키면 답이 제대로 나오니 ?

2018-09-02 12:21 UTC, sirupe commented on yeonjong/src/chapter03/Loop2.java
> +            userInputNumber = userInputNumber / DIVISION_NUMBER;
ok

2018-09-02 12:22 UTC, sirupe commented on yeonjong/src/chapter03/Loop2.java
> +    public void sumEach(int userInputNumber) {
ok

2018-09-02 12:25 UTC, sirupe commented on yeonjong/src/common/UserInput.java
> +
공백제거

2018-09-02 12:25 UTC, sirupe commented on yeonjong/src/common/UserInput.java
> +
공백제거

2018-09-02 12:57 UTC, shinyeonjong commented on yeonjong/src/common/UserInput.java
> +
수정했습니다.

2018-09-02 12:57 UTC, shinyeonjong commented on yeonjong/src/common/UserInput.java
> +
수정했습니다.

2018-09-02 12:58 UTC, shinyeonjong commented on yeonjong/src/chapter03/Loop.java
> +            int sumValue = i;
오마이갓. 수정했습니다.

2018-09-02 12:58 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +            if (selectedMenu == Loop.FINISH) {
수정했습니다

2018-09-02 12:59 UTC, shinyeonjong commented on yeonjong/src/chapter02/Operator.java
> +        execute();
```java
private boolean execute() {
        showMenu();
        int selectedMenu = UserInput.getUserInteger();
        if (isFinish(selectedMenu)) {
            return true;
        } else {
            int userInputValue = UserInput.getUserInteger();
            String result = executeQuestionBy(selectedMenu, userInputValue);
            print(result);
            return false;
        }
    }
```
수정했습니다.

2018-09-02 13:04 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +        execute();
ok

2018-09-02 13:04 UTC, sirupe commented on yeonjong/src/chapter02/Operator.java
> +            if (selectedMenu == Loop.FINISH) {
ok

2018-09-02 13:04 UTC, sirupe commented on yeonjong/src/chapter03/Loop.java
> +            int sumValue = i;
ok

2018-09-02 13:04 UTC, sirupe commented on yeonjong/src/common/UserInput.java
> +
ok

2018-09-02 13:04 UTC, sirupe commented on yeonjong/src/common/UserInput.java
> +
ok

2018-09-02 13:05 UTC, sirupe approved these changes
고생 했어. 
첫 머지 축하해.

2018-09-02 13:05 UTC, merged

2018-09-02 13:05 UTC, shinyeonjong commented
야호~