연산자 문제 올립니다.
howCanWeDoVeryWell/CodeReview pull request #8
Opened 2018-08-21 13:18 UTC by jsjjjj

확인 부탁드립니다.

2018-08-21 15:22 UTC, sirupe approved these changes
리뷰 확인 바랍니다.

2018-08-21 15:22 UTC, sirupe commented on sujin/src/homework/operator/CommonCalculatingExpression.java
> +public class CommonCalculatingExpression {
연산자 공통 코드 ..? 어떤 연산을 하기 위한 클래스입니까?

2018-08-21 15:22 UTC, sirupe commented on sujin/src/homework/operator/CommonCalculatingExpression.java
> +    public Boolean doCalculate(String userInput, Boolean isThatWords) {
역시.. 어떤 계산을 하기 위한 메소드입니까 ?

2018-08-21 15:22 UTC, sirupe commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +	void CalculateFahrenheitToCelsius(Scanner scanner) {
스캐너를 구지 파라미터로 받은 이유가 뭐죠?

2018-08-21 15:22 UTC, sirupe commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +			isThatHundredsNumber = commonCalculatingExpression.doCalculate(userInputNumber, isThatHundredsNumber);
위에서 보았던 Common 클래스 같은데 여기서 왜 구지 이 클래스의 메소드를 사용하는건지 잘 모르겠습니다. 그리고 doCalculate() 의 결과값이 boolean 변수에 들어갈 수 있다는 것은 boolean 을 반환한다는 것인데 그렇다면 왜 메소드명이 is... 로 시작하지 않는 것인지 궁금합니다.

2018-08-21 15:22 UTC, sirupe commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +				double stringConvertToInt = Double.parseDouble(userInputNumber);
변수명이 stringConvertToInt 인데 자료형은 double 이네요 ..?

2018-08-21 15:22 UTC, sirupe commented on sujin/src/homework/operator/HundredsUnitRoundOff.java
> +	void doCalculateChangingNumberOneUnitToOne(Scanner scanner) {
메소드의 접근제한자는 따로 없습니까? 그리고 do 도 동사, calculate 도 동사, changing 은 동명사.. 무엇을 하는 메소드인지 잘 모르겠습니다.

2018-08-21 15:22 UTC, sirupe commented on sujin/src/homework/operator/HundredsUnitRoundOff.java
> +			if(userInputNumber.length() != 3) {
숫자 3에 무슨 의미가 있습니까? 왜 구지 3과 비교하나요?

2018-08-21 15:22 UTC, sirupe commented on sujin/src/homework/operator/HundredsUnitRoundOff.java
> +				int changedNumber = stringConvertToInt / 100 * 100;
이 곳의 100도 여기까지 코드를 읽어내려왔으면 왜 숫자 100으로 나누고 곱하는지 기억하기가 어렵습니다.

2018-08-21 15:26 UTC, imcts requested changes
1. 메소드 뒤에 공백 추가. 
2. if문 뒤에 공백 추가 
3. 반복문 뒤에 공백 추가. 
4. 문 뒤에 공백 추가. 
5. 3항연산자 컨벤션 다시 맞춰 작성. 

전체적으로 코드를 다 갖다가 복사 붙여넣기 했고 그 코드가 그 코드라 보다가 중지함. 

한번만 더 코드 복사 붙여넣기 하다 걸리면 진짜 가만 안둠.

메소드는 값을 전달받아서 해야할 일만 하고 결과값만 반환해야 하는데 그걸 못 지킴. 메소드 안에서 전부 사용자의 입력을 다 받으면서 진행하다 보니 코드 읽기 너무 힘들고 온갖 군데에 중복 코드가 난립함. 

사용자 입력은 메인메소드에서 받고 받은 값의 유효성 검사는 별도의 메소드에서 진행하고 그 다음 그 값을 메소드에 전달해서 메소드가 결과값을 반환하고 출력하는 코드로 변경하도록.

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +class ConversionFahrenheitToCelsiusCalculator {
클래스는 무슨 일을 하는 틀을 나타내는건데 이건 지금 변환하는것 화씨를 섭씨로 계산기인데. 뭐하자는건지 모르겠음.  그냥 단순히 온도 변환기 정도면 되는거 아님 ?

`TemperatureCalculator` 정도면 될듯.

이러면 온도 계산기 안에서 어떤 계산을 할지는 메소드 명으로 나타낼 수 있음.

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +	void CalculateFahrenheitToCelsius(Scanner scanner) {
왜 메소드명이 대문자로 시작하지? 그리고 메소드 선언 뒤에는 공백 문자열 추가.
그리고 메소드명은 계산이 아니라 이 경우에는 변환하는 것이므로 
`convertFahrenheitToCelsius`정도가 맞을듯

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +		while(true) {
반복문 뒤에 중괄호전 공백 추가.

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/CommonCalculatingExpression.java
> +public class CommonCalculatingExpression {
이런 경우에는 패키지로 구분을 해서 common 패키지를 놔두던지 해야지 왜 클래스명에 Common이 들어가야하지.
그리고 이 클래스는 공통 계산 표현이라는 클래스인데 이게 맞어 ? 이럴거면 
/common/클래스명이 되어야 하는데 이 클래스명은 의미 전달이 전혀 안됨.

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/CommonCalculatingExpression.java
> +    public Boolean doCalculate(String userInput, Boolean isThatWords) {
do 동사 calculate 동사. 
 
그래서 이 메소드가 하는게 뭔지 알 수 없음.

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/CommonCalculatingExpression.java
> +            char stringConvertToChar = userInput.charAt(i);
이미 `charAt`으로 컨버팅한 결과값 아님 ? 왜 변수명이 stringConvertToChar인건지 ?

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/CommonCalculatingExpression.java
> +            if(!(stringConvertToChar >= 48 && stringConvertToChar <= 57)) {
```java
 if(!(stringConvertToChar >= 48 && stringConvertToChar <= 57)) {} // 왜 조건문 앞에 !연산을 한번 더 하는거지
```

```java
 if(stringConvertToChar <= 48 && stringConvertToChar >= 57) {} 
```

이렇게 풀면 안될 이유라도?

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/CommonCalculatingExpression.java
> +            if(!(stringConvertToChar >= 48 && stringConvertToChar <= 57)) {
그리고 48이랑 57은 상수로 뺄 것.

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/CommonCalculatingExpression.java
> +                if(userInput.charAt(i) == 45)  {
45는 어디서 튀어나온건지 모르겠고 굳이 45일때 조건절까지 걸어서 continue를 해야 하는걸까.

```java
if (userInput.charAt(i) != 45) {
  isTharWords = false;
}
```

면 될거 같은데.

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/CommonCalculatingExpression.java
> +                if(userInput.charAt(i) == 45)  {
if 뒤에 공백 추가

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +			Boolean isThatHundredsNumber = true;
일단 That 필요 없음 그리고 HundredsNumber를 입력받는 Boolean이 왜 필요한지 모르겠음.

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +			isThatHundredsNumber = commonCalculatingExpression.doCalculate(userInputNumber, isThatHundredsNumber);
`isThatHundredsNumber `이거 대체 왜 인자로 넘기는데?

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +			if(!isThatHundredsNumber) {
```java
if (!commonCalculatingExpression.doCalculate(userInputNumber, isThatHundredsNumber)) {
   // do some codes
}
```

이렇게 해도 충분할 뿐더러 저 `isThatHundredsNumber`는 불필요함. 대체 왜 인자로 넘겨야 되는데 ?

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +			CommonCalculatingExpression commonCalculatingExpression = new CommonCalculatingExpression();
공통이면 ConversionFahrenheitToCelsiusCalculator 를 static으로 만들던가 클래스를 아니면 ConversionFahrenheitToCelsiusCalculator 생성자에서 생성을 하던가 메소드 실행할때마다 공통으로 사용하는 애를 만들어서 쓰나 ?

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +				double stringConvertToInt = Double.parseDouble(userInputNumber);
자료형은 double이고 변수명은 문자열을 인트로 컨버트하고 뭐하자는건데 이거.
그리고 유저 입력값을 왜 더블로 파싱하는데 ? 아무 생각 안하고 코드 짤래 진짜? 
내가 복붙 하지 말랬지 ? 똑같은 코드니까 일단 복붙하고 자료형 바꾸면 모를 줄 알았냐?

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +				double changedNumber = 5.0 / 9 * (stringConvertToInt - 32);
심지어 밑에서는 int형인 32랑 사칙연산 하는데 위에는 더블이네 ?

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +				double changedNumber = 5.0 / 9 * (stringConvertToInt - 32);
1. 5.0
2. 9
3. 32 

전부 상수로 뺄것

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +				double changedNumber = 5.0 / 9 * (stringConvertToInt - 32);
changedNumber가 아니라 계산된 결과값이겠지. 뭐가 바뀌었다는거야 원래 값이 없었다가 새로 생긴건데. 
result 또는 calculatedTemperature 겠지

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +		Scanner scanner = new Scanner(System.in);
질문. Scanner는 여기에서 생성하고 값도 여기에서 입력 받는데 왜 scanner를 메소드에 인자로 넘겨주고 저 메소드 안에서 입력 받고 계산까지 다 하지 ?

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +		Scanner scanner = new Scanner(System.in);
`CalculateFahrenheitToCelsius`에서는 입력받은 값을 가지고 계산만 해야 되는게 아닌가?

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/HundredsUnitRoundOff.java
> +class HundredsUnitRoundOffCalculator {
`DumpCalculator`면 충분할듯

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +			String userInputNumber = scanner.nextLine();
0넣으면 어떻게 되는데

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/HundredsUnitRoundOff.java
> +	void doCalculateChangingNumberOneUnitToOne(Scanner scanner) {
`doCalculateChangingNumberOneUnitToOne` 메소드가 하는 일만 기술할 것. 
더군다나 지금 이 메소드 이름자체도 잘못됨. 한다. 계산한다. 바꾸는것 숫자 하나 유닛을 하나로 이걸 누가 이해하냐 ?
그리고 이 메소드는 그것 뿐만이 아닌데? 사용자한테 값도 입력 받고 있지? 거기다가 계산도 하고 있지? 유효성 검사도 하고 있지? 어딜봐서 이 메소드가 하는 일이 그거야 ? 다른곳도 다 마찬가지임.

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/HundredsUnitRoundOff.java
> +				return;
왜 void인데 return을 하지? break가 맞는거 아닐까

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/VariableExam2.java
> +public class VariableExam2 {
뭐 하다가 이번에는 VariableExam2냐?

2018-08-21 15:26 UTC, imcts commented on sujin/src/homework/operator/VariableExam2.java
> +	void doCalculateChangingNumberOneUnitToOne(Scanner scanner) {
할말하않.

2018-08-21 15:50 UTC, shinyeonjong reviewed
확인 부탁드려요

2018-08-21 16:21 UTC, sirupe requested changes
리뷰 확인 부탁드립니다.

2018-08-23 15:54 UTC, jsjjjj commented on sujin/src/homework/operator/CommonCalculatingExpression.java
> +public class CommonCalculatingExpression {
숫자가 아닐 때 validation check하는 클래스 인데 .. 제가 잘 못 만든거같아요
다시 만들어볼게요

2018-08-23 15:54 UTC, jsjjjj commented on sujin/src/homework/operator/CommonCalculatingExpression.java
> +    public Boolean doCalculate(String userInput, Boolean isThatWords) {
수정하겠습니다 ..^^

2018-08-23 15:56 UTC, jsjjjj commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +	void CalculateFahrenheitToCelsius(Scanner scanner) {
제가 작성 했을 당시에 Scanner선언이랑 입력 받는 거랑 다르다고 생각을 해서 CalculateFahrenheitToCelsius메소드에 Scanner를 받고 그 안에 입력을 받았씁니다.
더 명시적이게 수정해보겠습니다.

2018-08-23 15:57 UTC, jsjjjj commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +			isThatHundredsNumber = commonCalculatingExpression.doCalculate(userInputNumber, isThatHundredsNumber);
으흠. class를 new해도 되지않는 문젠뎅.. 수정하겠습니다.
Boolean도 수정할게요

2018-08-23 15:57 UTC, jsjjjj commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +				double stringConvertToInt = Double.parseDouble(userInputNumber);
수정하겠습니다.

2018-08-23 15:59 UTC, jsjjjj commented on sujin/src/homework/operator/HundredsUnitRoundOff.java
> +				int changedNumber = stringConvertToInt / 100 * 100;
넹. 수정해볼게여.!

2018-08-23 15:59 UTC, jsjjjj commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +class ConversionFahrenheitToCelsiusCalculator {
네 수정하겠씁니다.

2018-08-23 16:00 UTC, jsjjjj commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +	void CalculateFahrenheitToCelsius(Scanner scanner) {
네 수정하겠습니다.

2018-08-23 16:00 UTC, jsjjjj commented on sujin/src/homework/operator/CommonCalculatingExpression.java
> +    public Boolean doCalculate(String userInput, Boolean isThatWords) {
넹..ㅎ 수정하겠습니다.

2018-08-23 16:00 UTC, jsjjjj commented on sujin/src/homework/operator/CommonCalculatingExpression.java
> +public class CommonCalculatingExpression {
아하.! 수정하겠습니다.

2018-08-23 16:00 UTC, jsjjjj commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +		while(true) {
수정하겠습니다.

2018-08-23 16:01 UTC, jsjjjj commented on sujin/src/homework/operator/HundredsUnitRoundOff.java
> +	void doCalculateChangingNumberOneUnitToOne(Scanner scanner) {
아.ㅎ 수정할게요

2018-08-23 16:03 UTC, jsjjjj commented on sujin/src/homework/operator/HundredsUnitRoundOff.java
> +				return;
아. return이랑 break랑 제가 쓰다보니깐 궁금해서 차이점이 뭔가 해서 찾아봤는데..
return은 아예 main을 끝내는 거고 break는 그 문만 끝낸다고 찾았어서

아예 끝내고 싶어서 return으로 했었씁니다.. .. ^^
다시 찾아서 해볼게요

2018-08-23 16:03 UTC, jsjjjj commented on sujin/src/homework/operator/VariableExam2.java
> +public class VariableExam2 {
수정할게욤..

2018-08-23 16:03 UTC, jsjjjj commented on sujin/src/homework/operator/VariableExam2.java
> +	void doCalculateChangingNumberOneUnitToOne(Scanner scanner) {
넹 ~ ><

2018-08-23 16:04 UTC, jsjjjj commented on sujin/src/homework/operator/ConversionFahrenheitToCelsius.java
> +			String userInputNumber = scanner.nextLine();
0넣으면.. 확인해볼게영. .. ㅎ..

2018-08-23 16:05 UTC, jsjjjj commented on sujin/src/homework/operator/HundredsUnitRoundOff.java
> +			if(userInputNumber.length() != 3) {
세글자가 아니면 다시 입력 하라고 정의 해논거였는데 .. 유동적이게 해보겠습니다..ㅎ..

2018-08-28 11:58 UTC, closed without merging