반복문 문제 올립니다.
howCanWeDoVeryWell/CodeReview pull request #9
Opened 2018-08-21 13:43 UTC by jsjjjj

확인 부탁드립니다.

2018-08-21 15:10 UTC, sirupe approved these changes
리뷰 확인 부탁드립니다.

2018-08-21 15:10 UTC, sirupe commented on sujin/src/homework/loop/DiceExam.java
> +class DiceTotalCalculator {
total 은 형용사, dice 는 명사. 형용사는 명사 앞에서 명사를 꾸미므로 total 이 앞에 오는 것이 좋다고 생각합니다.

2018-08-21 15:10 UTC, sirupe commented on sujin/src/homework/loop/DiceExam.java
> +				if(i + j == 6) {
실행해보지는 않았는데 이렇게 체크하면 답이 제대로 나옵니까? 예를 들어 i = 2, j = 4 인 경우와 i = 4, j = 2 인 경우는 중복되는 경우의 수가 되는 것은 아닌가요?

2018-08-21 15:10 UTC, sirupe commented on sujin/src/homework/loop/DiceExam.java
> +		diceTotalCalculator.calculateTotalSum();
단순히 실행결과만 확인할것이라면 구지 변수를 선언하여 할당할 필요가 있나 싶습니다.

2018-08-21 15:10 UTC, sirupe commented on sujin/src/homework/loop/TotalSum.java
> +			if(!(i%2 == 0 || i%3 == 0)) {
연산자와 연산되는 수 사이에는 공백을 꼭 띄워주시길 바랍니다.

2018-08-21 15:10 UTC, sirupe commented on sujin/src/homework/loop/loopExam.java
> +class loopCalculator {
클래스명은 소문자로 시작하지 않는 것으로 알고 있습니다.

2018-08-21 15:10 UTC, sirupe commented on sujin/src/homework/loop/loopSumTotalExam.java
> +public class loopSumTotalExam {
여기도 클래스명이 소문자로 시작하네요.

2018-08-21 15:34 UTC, imcts reviewed
확인요망.

2018-08-21 15:34 UTC, imcts commented on sujin/src/homework/loop/TotalSum.java
> +			if(!(i%2 == 0 || i%3 == 0)) {
for 뒤에도 공백 추가.

2018-08-21 15:34 UTC, imcts commented on sujin/src/homework/loop/TotalSum.java
> +			if(!(i%2 == 0 || i%3 == 0)) {
if 뒤에도 공백 추가

2018-08-21 15:34 UTC, imcts commented on sujin/src/homework/loop/TotalSum.java
> +				System.out.println(i);
i를 왜 계속 출력하지? 테스트할때 쓰던 코드를 우리가 봐야하나?

2018-08-21 15:34 UTC, imcts commented on sujin/src/homework/loop/loopExam.java
> +	void doCalculator() {
하다 계산기. 메소드명이 이상함. 그래서 이 메소드는 뭘 하는 메소드지. 계산하는 메소드인가 출력하는 메소드인가.
계산을 하면 결과를 반환해야 할 텐데 그것도 아니고.

2018-08-21 15:34 UTC, imcts commented on sujin/src/homework/loop/loopSumTotalExam.java
> +	void doCalculator() {
복사붙여넣기 메소드명 마찬가지. 하다 계산기.

2018-08-21 15:34 UTC, imcts commented on sujin/src/homework/loop/loopSumTotalExam.java
> +		int index = 0;
인덱스가 1부터 시작하면 되는거 아닌가

2018-08-21 15:35 UTC, imcts requested changes
확인요망.

2018-08-21 15:59 UTC, shinyeonjong commented on sujin/src/homework/loop/DiceExam.java
> +				if(i + j == 6) {
저 경우도 경우의 수 한가지 아닐까요?
(1, 5) / ( 2, 4) / (3, 3) / (4, 2)/ (5, 1)

2018-08-21 16:12 UTC, jsjjjj commented on sujin/src/homework/loop/DiceExam.java
> +class DiceTotalCalculator {
아 수정하겠습니다.

2018-08-21 16:15 UTC, jsjjjj commented on sujin/src/homework/loop/DiceExam.java
> +				if(i + j == 6) {
음 연종이가 말했듯이 경우의 수니깐 중복이라고 할 수 없지 않을까요??..!!!
값은 (1, 5) / ( 2, 4) / (3, 3) / (4, 2)/ (5, 1) 이렇게 나오긴 합니다.

2018-08-21 16:15 UTC, jsjjjj commented on sujin/src/homework/loop/TotalSum.java
> +			if(!(i%2 == 0 || i%3 == 0)) {
네 알겠습니다.

2018-08-21 16:22 UTC, sirupe requested changes
리뷰 확인 부탁드립니다.

2018-08-21 17:11 UTC, jsjjjj commented on sujin/src/homework/loop/TotalSum.java
> +				System.out.println(i);
수정하겠습니다.

2018-08-21 17:12 UTC, jsjjjj commented on sujin/src/homework/loop/loopSumTotalExam.java
> +public class loopSumTotalExam {
수정하겠습니다..

2018-08-21 17:16 UTC, jsjjjj commented on sujin/src/homework/loop/loopExam.java
> +	void doCalculator() {
메소드..이름 어렵군염
수정하겠습니다

2018-08-21 17:16 UTC, jsjjjj commented on sujin/src/homework/loop/loopSumTotalExam.java
> +	void doCalculator() {
넹.. 수정하겠습니다.

2018-08-22 14:08 UTC, jsjjjj commented on sujin/src/homework/loop/loopExam.java
> +class loopCalculator {
네 수정할게여

2018-08-28 11:58 UTC, closed without merging